In [ ]:
import pandas as pd

In [ ]:
# Carregando e lendo o dataset
df_textos = pd.read_csv('/content/drive/MyDrive/Dataset p  TF-IDF e Similaridade de Cosseno/CNN_Articels_clean.csv')  # Insira o dataset enviado no e-mail
df_textos.head()

print(f'O dataframe tem {df_textos.shape[0]} linhas e {df_textos.shape[1]} colunas')

df_textos.columns
list(df_textos.columns)

O dataframe tem 37949 linhas e 11 colunas


['Index',
 'Author',
 'Date published',
 'Category',
 'Section',
 'Url',
 'Headline',
 'Description',
 'Keywords',
 'Second headline',
 'Article text']

In [ ]:
#Criação de objeto para dataset em lista

titulos = []
texto = []

termo_pesquisa=input('Insira o termo (em inglês) para encontrar as notícias mais relevantes ao tema (exemplo: bitcoin, Trump, US election, COVID-19): ')

text_limit = 28000 #limitado para esse número para evitar o alto consumo de ram e/ou erro do arquivo.

titulos.append(termo_pesquisa)
texto.append(termo_pesquisa)
titulos.extend(df_textos['Headline'].iloc[:text_limit].values)
texto.extend(df_textos['Description'].iloc[:text_limit].values)

Insira o termo (em inglês) para encontrar as notícias mais relevantes ao tema (exemplo: bitcoin, Trump, US election, COVID-19): US election


In [ ]:
#Panorama de TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

stopwords_adicionais = ['english', '- CNN']  # Para acionar as stopwords e o termo de exclusão
vetor = TfidfVectorizer(stop_words=stopwords_adicionais)
vetor.fit(texto)
vetor.vocabulary_
vetor_features = vetor.transform(texto)
vetor_features_array = vetor_features.toarray()

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:406: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['cnn'] not in stop_words.
  warnings.warn(


In [ ]:
#Função para iniciar uma possível chamada à notícia com similaridade de cosseno
import numpy
simi_cosse = cosine_similarity(vetor_features_array, [vetor_features_array[0]])  # Calcular similaridade // Fatiamento dentro dos vetores
lista_similaridades = simi_cosse.flatten().tolist() #transformá-los para um vetor simples e evitar erro na hora da execução // passar esses vetores para uma lista
similar_indices = sorted(range(len(lista_similaridades)), key=lambda i: lista_similaridades[i], reverse=True)[1:6]# retorna os cinco mais similares em ordem decrescente

#Linha para consulta dos valores similares mais importantes
termos_similares = [(titulos[i], simi_cosse[i], lista_similaridades[i]) for i in similar_indices]

In [ ]:
termos_similares

[("Alabama judge denies Roy Moore's complaint - CNNPolitics",
  array([0.36766381]),
  0.3676638140601371),
 ('Election results: Donald Trump, MLK Jr. and the backlash against progress - CNN',
  array([0.36174503]),
  0.36174502536573855),
 ('Poland edges further right in election - CNN',
  array([0.33513112]),
  0.335131124730348),
 ('Putin registered as candidate for Russian president - CNN',
  array([0.33417448]),
  0.3341744822545604),
 ("House Democrats call on Justice Department to address 'insider threats' posed by candidates who believe false election fraud claims  - CNNPolitics",
  array([0.32957109]),
  0.32957109279442853)]

In [ ]:
# Retornar os textos correspondentes
print("Textos mais similares:")
for i in similar_indices:
    print(f"- {titulos[i]}")

Textos mais similares:
- Alabama judge denies Roy Moore's complaint - CNNPolitics
- Election results: Donald Trump, MLK Jr. and the backlash against progress - CNN
- Poland edges further right in election - CNN
- Putin registered as candidate for Russian president - CNN
- House Democrats call on Justice Department to address 'insider threats' posed by candidates who believe false election fraud claims  - CNNPolitics
